---

name: Standard-Check

on: push

jobs:
  standard-check:
    name: code style check
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Run Standard-Check
        uses: github/super-linter@v4.8.6
        env:
          DEFAULT_BRANCH: main
